name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build
        run: |
          yarn install
          yarn build

      - name: Github Pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          # Git branch where assets will be deployed
          target_branch: gh-pages
          # Create incremental commit instead of doing push force
          keep_history: true
          # Build directory to deploy
          build_dir: dist
