name: Build to Github Pages

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v1.1.0
        with:
          node-version: 'lts'
      
      - name: Install dependencies
        run: yarn install
       
      - name: Build
        run: yarn build

      - name: Deploy to Github Pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          # Git branch where assets will be deployed
          target_branch: gh-pages
          # Create incremental commit instead of doing push force
          keep_history: true
          # Build directory to deploy
          build_dir: dist
